version: '3'
services:

  #PHP Service
  app:
    image: registry.gitlab.com/fsin/cab:latest
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
       - ./:/var/www/html/cab
      #  - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: prod
    working_dir: /var/www/html/cab
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/cab
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge